name: Generate RSS feeds

on:
  schedule:
  - cron: "0 17 * * 1-5"

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Parse 'Bürgerportal - Aktuelle Meldungen'
        run: python parsers/buergerportal-aktuelle_meldungen.py
      - name: Parse 'Bürgerportal - Stadtentwicklung - Aktuelle Verfahren'
        run: python parsers/buergerportal-stadtentwicklung-aktuelle_verfahren.py
      - name: Parse 'Bürgerportal - Stadtentwicklung - Bauleitpläne'
        run: python parsers/buergerportal-stadtentwicklung-bauleitplaene.py
      - name: Parse 'Bürgerportal - Stadtentwicklung - Klima und Umwelt'
        run: python parsers/buergerportal-stadtentwicklung-klima_und_umwelt.py
      - name: Parse 'Bürgerportal - Stadtentwicklung - Konzepte'
        run: python parsers/buergerportal-stadtentwicklung-konzepte.py
      - name: Parse 'Maerker Portal'
        run: python parsers/maerker-portal_luckau.py
      - name: Parse 'Kultur & Stadtleben - Veranstatltungskalender'
        run: python parsers/kultur_stadtleben-veranstaltungskalender.py
      - name: Publish
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: feeds
          FOLDER: generated-rss
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SKIP_EMPTY_COMMITS: true
          
